package org.example.Model.Controller;
// Generated by Qodo Gen

import org.example.Controller.ContactsController;

import org.example.Model.AbstractRecord;
import org.example.Model.Organization;
import org.example.Model.Person;
import org.example.Model.Phonebook;
import org.example.View.ContactsView;
import org.junit.Test;
import org.mockito.Mockito;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

public class ContactsControllerTest {


    // Adding a new person contact with valid input data
    @Test
    public void test_add_person_contact_with_valid_data() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput())
            .thenReturn("person")
            .thenReturn("John")
            .thenReturn("Smith") 
            .thenReturn("1990-01-01")
            .thenReturn("M")
            .thenReturn("1234567890");

        when(phonebook.verifybirthDate("1990-01-01")).thenReturn(LocalDate.of(1990, 1, 1));
        when(phonebook.verifyGender("M")).thenReturn(true);

        controller.handleAddContact();

        verify(view).showMessage("Enter the type (person, organization):");
        verify(view).showMessage("Enter the name:");
        verify(view).showMessage("Enter the surname:");
        verify(view).showMessage("Enter the birth date:");
        verify(view).showMessage("Enter the gender (M, F): ");
        verify(view).showMessage("Enter the number:");
        verify(phonebook).addContact(any(Person.class));
    }

    // Adding contact with invalid contact type
    @Test
    public void test_add_contact_with_invalid_type() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput()).thenReturn("invalid_type");

        controller.handleAddContact();

        verify(view).showMessage("Enter the type (person, organization):");
        verify(view).showMessage("No valid action");
        verify(phonebook, never()).addContact(any());
    }

    // Adding a new organization contact with valid input data
    @Test
    public void test_add_organization_contact() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput()).thenReturn("organization", "Tech Corp", "123 Tech Street", "+1234567890");

        controller.handleAddContact();

        verify(phonebook).addContact(any(Organization.class));
    }

    // Listing all contacts when phonebook is not empty
    /*
    @Test
    public void test_list_contacts_non_empty_phonebook() {
        Phonebook phonebook = mock(Phonebook.class);

        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        List<AbstractRecord> contacts = List.of(mock(AbstractRecord.class));
        when(phonebook.getContactsList()).thenReturn(contacts);
        phonebook.cleardb();
        controller.handleListContacts();

        verify(view).showListMenu();
        verify(view, times(contacts.size())).showMessage(anyString());
    }*/

    // Searching contacts with existing query string
    /*
    @Test
    public void test_search_contacts_with_existing_query() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        List<AbstractRecord> results = List.of(mock(AbstractRecord.class));
        when(view.getUserInput()).thenReturn("John");
        when(phonebook.searchContacts("John")).thenReturn(results);

        controller.handleSearchContacts();

        verify(view).showSearchMenu();
        verify(view, times(results.size())).showMessage(anyString());
    }*/

    // Editing person contact fields with valid input
    /*
    @Test
    public void test_edit_person_contact_fields() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Person person = new Person("John", "Doe", "+1234567890", "M", LocalDate.of(1990, 1, 1));
        Mockito.when(phonebook.getContact(0)).thenReturn(person);
        Mockito.when(view.getUserInput()).thenReturn("name", "Jane");

        controller.editContact(0);

        assertEquals("Jane", person.getName());
        Mockito.verify(view).showMessage("Contact updated.");
    }
*/
    // Editing organization contact fields with valid input
    /*
    @Test
    public void test_edit_organization_contact_fields() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Organization organization = new Organization("Tech Corp", "123 Tech Street", "+1234567890");
        Mockito.when(phonebook.getContact(0)).thenReturn(organization);
        Mockito.when(view.getUserInput()).thenReturn("address", "456 New Tech Street");

        controller.editContact(0);

        assertEquals("456 New Tech Street", organization.getAddress());
        Mockito.verify(view).showMessage("Contact updated.");
    }*/

    // Deleting an existing contact
  /*  @Test
    public void test_delete_existing_contact() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        List<AbstractRecord> contacts = new ArrayList<>();
        Person person = new Person("John", "Doe", "+1234567890", "M", LocalDate.of(1990, 1, 1));
        contacts.add(person);
        Mockito.when(phonebook.getContactsList()).thenReturn(contacts);

        controller.recordsActions("delete", 0);

        Mockito.verify(phonebook).deleteContact(0);
        Mockito.verify(view).showMessage("Contact deleted");
    }*/

    // Counting total number of contacts
    @Test
    public void test_count_contacts() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(phonebook.countContacts()).thenReturn(5);

        controller.handleCountContacts();

        Mockito.verify(view).showMessage("The Phone Book has 5 records.");
    }

    // Adding person with invalid gender input
    @Test
    public void test_add_person_invalid_gender() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(view.getUserInput())
               .thenReturn("person", "John", "Doe", "1990-01-01", "X", "1234567890");

        controller.handleAddContact();

        Mockito.verify(phonebook).addContact(Mockito.argThat(person -> 
            person instanceof Person && ((Person) person).getGender().equals("")
        ));
    }

    // Adding person with invalid birth date format
    @Test
    public void test_add_person_invalid_birth_date() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(view.getUserInput())
               .thenReturn("person", "John", "Doe", "invalid-date", "M", "1234567890");

        controller.handleAddContact();

        Mockito.verify(phonebook).addContact(Mockito.argThat(person -> 
            person instanceof Person && ((Person) person).getBirthDate() == null
        ));
    }
}