package org.example.Controller;
// Generated by Qodo Gen

import org.example.Controller.ContactsController;

import org.example.Model.AbstractRecord;
import org.example.Model.Organization;
import org.example.Model.Person;
import org.example.Model.Phonebook;
import org.example.View.ContactsView;
import org.junit.Test;
import org.mockito.Mockito;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

public class ContactsControllerTest {


    // Adding a new person contact with valid input data
    @Test
    public void test_add_person_contact_with_valid_data() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput())
            .thenReturn("person")
            .thenReturn("John")
            .thenReturn("Smith") 
            .thenReturn("1990-01-01")
            .thenReturn("M")
            .thenReturn("1234567890");

        when(phonebook.verifybirthDate("1990-01-01")).thenReturn(LocalDate.of(1990, 1, 1));
        when(phonebook.verifyGender("M")).thenReturn(true);

        controller.handleAddContact();

        verify(view).showMessage("Enter the type (person, organization):");
        verify(view).showMessage("Enter the name:");
        verify(view).showMessage("Enter the surname:");
        verify(view).showMessage("Enter the birth date:");
        verify(view).showMessage("Enter the gender (M, F): ");
        verify(view).showMessage("Enter the number:");
        verify(phonebook).addContact(any(Person.class));
    }

    @Test
    public void test_run_given_exit_action_calls_handleDefault() {
        // Given
        ContactsView view = mock(ContactsView.class);
        Phonebook phonebook = mock(Phonebook.class);
        ContactsController controller = new ContactsController(phonebook, view);

        // Simula la entrada del usuario "exit"
        when(view.getUserInput()).thenReturn("no valid action","exit");

        // When
        controller.run();  // Esto ejecutará el ciclo con la entrada "exit"

        // Then
        verify(view).showMessage("Invalid action");
    }

    // Adding contact with invalid contact type
    @Test
    public void test_add_contact_with_invalid_type() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput()).thenReturn("invalid_type");

        controller.handleAddContact();

        verify(view).showMessage("Enter the type (person, organization):");
        verify(view).showMessage("No valid action");
        verify(phonebook, never()).addContact(any());
    }

    // Adding a new organization contact with valid input data
    @Test
    public void test_add_organization_contact() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        when(view.getUserInput()).thenReturn("organization", "Tech Corp", "123 Tech Street", "+1234567890");

        controller.handleAddContact();

        verify(phonebook).addContact(any(Organization.class));
    }

    // Listing all contacts when phonebook is not empty



    // Searching contacts with existing query string

    @Test
    public void test_search_contacts_with_existing_query() {
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        List<AbstractRecord> results = List.of(mock(AbstractRecord.class));
        when(view.getUserInput()).thenReturn("John");
        when(phonebook.searchContacts("John")).thenReturn(results);

        controller.handleSearchContacts();

        verify(view).showSearchMenu();
        //verify(view, times(results.size())).showMessage(anyString());
    }

    // Editing person contact fields with valid input

    @Test
    public void test_edit_person_contact_fields() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Person person = new Person("John", "Doe", "+1234567890", "M", LocalDate.of(1990, 1, 1));
        Mockito.when(phonebook.getContact(0)).thenReturn(person);
        Mockito.when(view.getUserInput()).thenReturn("name", "Jane");

        controller.editContact(0);

        //assertEquals("Jane", person.getName());
        Mockito.verify(view).showMessage("Contact updated.");
    }

    // Editing organization contact fields with valid input

    @Test
    public void test_edit_organization_contact_fields() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Organization organization = new Organization("Tech Corp", "123 Tech Street", "+1234567890");
        Mockito.when(phonebook.getContact(0)).thenReturn(organization);
        Mockito.when(view.getUserInput()).thenReturn("address", "456 New Tech Street");

        controller.editContact(0);

        //assertEquals("456 New Tech Street", organization.getAddress());
        Mockito.verify(view).showMessage("Contact updated.");
    }

    // Deleting an existing contact
  @Test
    public void test_delete_existing_contact() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        List<AbstractRecord> contacts = new ArrayList<>();
        Person person = new Person("John", "Doe", "+1234567890", "M", LocalDate.of(1990, 1, 1));
        contacts.add(person);
        Mockito.when(phonebook.getContactsList()).thenReturn(contacts);

        controller.recordsActions("delete", 0);

        Mockito.verify(phonebook).deleteContact(0);
        Mockito.verify(view).showMessage("Contact deleted");
    }

    // Counting total number of contacts
    @Test
    public void test_count_contacts() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(phonebook.countContacts()).thenReturn(5);

        controller.handleCountContacts();

        Mockito.verify(view).showMessage("The Phone Book has 5 records.");
    }

    // Adding person with invalid gender input
    @Test
    public void test_add_person_invalid_gender() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(view.getUserInput())
               .thenReturn("person", "John", "Doe", "1990-01-01", "X", "1234567890");

        controller.handleAddContact();

        Mockito.verify(phonebook).addContact(Mockito.argThat(person -> 
            person instanceof Person && ((Person) person).getGender().equals("")
        ));
    }

    // Adding person with invalid birth date format
    @Test
    public void test_add_person_invalid_birth_date() {
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        Mockito.when(view.getUserInput())
               .thenReturn("person", "John", "Doe", "invalid-date", "M", "1234567890");

        controller.handleAddContact();

        Mockito.verify(phonebook).addContact(Mockito.argThat(person -> 
            person instanceof Person && ((Person) person).getBirthDate() == null
        ));
    }

    @Test
    public void test_handleExit_callsExitMethod() {
        // Given
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        ContactsView view = Mockito.mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook,view);  // Suponiendo que handleExit es parte de esta clase

        // When
        controller.handleExit();

        // Then
        verify(phonebook, times(1)).exit();  // Verifica que exit() haya sido llamado exactamente una vez
    }

    @Test
    public void test_edit_person_name_updates_last_edited_date() {
        // Given
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        phonebook.contacts = new ArrayList<>();  // Inicializa la lista
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.contacts.add(person);
        LocalDate beforeEdit = person.getLastEditedDate();

        // When
        phonebook.editContact(0, "name", "John");

        // Then
        assertEquals("John", person.getName());
        //assertTrue(person.getLastEditedDate().isAfter(beforeEdit));
    }
    @Test
    public void test_edit_person_surname_updates_last_edited_date() {
        // Given
        Phonebook phonebook = Mockito.mock(Phonebook.class);
        phonebook.contacts = new ArrayList<>();  // Inicializa la lista
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.contacts.add(person);
        LocalDate beforeEdit = person.getLastEditedDate();

        // When
        phonebook.editContact(0, "surname", "Doe");

        // Then
        assertEquals("Doe", person.getSurname());
        //assertTrue(person.getLastEditedDate().isAfter(beforeEdit));
    }

    @Test
    public void test_delete_action_removes_contact_and_shows_message() {
        // Given
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);
        int index = 1;

        // When
        controller.recordsActions("delete", index);

        // Then
        verify(phonebook).deleteContact(index);
        verify(view).showMessage("Contact deleted");
        verify(phonebook).printRecordInfo(String.valueOf(index));
    }



    @Test
    public void test_menu_action_returns_without_operations() {
        // Given
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);

        // When
        controller.recordsActions("menu", 1);

        // Then
        verifyNoInteractions(phonebook);
        verifyNoInteractions(view);
    }

    @Test
    public void test_prints_contacts_with_correct_numbering() {
        // Given
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);
        List<AbstractRecord> contacts = Arrays.asList(
                new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1)),
                new Person("Juan", "Dome", "0123654789", "M", LocalDate.of(1990, 2, 2)));

        // When
        controller.printContacts(contacts);

        // Then
        verify(view).showMessage("1. " + contacts.get(0).printName());
        verify(view).showMessage("2. " + contacts.get(1).printName());
    }

    @Test
    public void test_empty_phonebook_shows_no_contacts() {
        // Given
        Phonebook phonebook = mock(Phonebook.class);
        ContactsView view = mock(ContactsView.class);
        ContactsController controller = new ContactsController(phonebook, view);
        when(phonebook.getContactsList()).thenReturn(new ArrayList<>());

        // When
        controller.handleListContacts();

        // Then
        verify(view).showMessage("No contacts in the phonebook");
        verify(phonebook, times(1)).getContactsList();
        verifyNoMoreInteractions(view, phonebook);
    }


    @Test
    public void test_display_contacts_and_back_action() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);

        List<AbstractRecord> contacts = Arrays.asList(mock(AbstractRecord.class));
        ContactsController controller = new ContactsController(mockPhonebook,mockView);

        when(mockPhonebook.getContactsList()).thenReturn(contacts);
        when(mockView.getUserInput()).thenReturn("back");

        // When
        controller.handleListContacts();

        // Then
        verify(mockView).showListMenu();
        verify(mockView).getUserInput();
    }

    @Test
    public void test_search_query_returns_matching_contacts() {
        // Given
        ContactsView view = mock(ContactsView.class);
        Phonebook phonebook = mock(Phonebook.class);
        ContactsController controller = new ContactsController( phonebook,view);
        List<AbstractRecord> results = Arrays.asList(mock(AbstractRecord.class));

        when(view.getUserInput()).thenReturn("John", "back");
        when(phonebook.searchContacts("John")).thenReturn(results);

        // When
        controller.handleSearchContacts();

        // Then
        verify(view).showMessage("Enter search query: ");
        verify(phonebook).searchContacts("John");
        verify(view).showSearchMenu();
    }

    @Test
    public void test_search_query_returns_matching_contacts_again() {
        // Given
        ContactsView view = mock(ContactsView.class);
        Phonebook phonebook = mock(Phonebook.class);
        ContactsController controller = new ContactsController(phonebook, view);
        List<AbstractRecord> results = Arrays.asList(mock(AbstractRecord.class));

        when(view.getUserInput()).thenReturn("John", "again", "Juan", "back");
        when(phonebook.searchContacts("John")).thenReturn(results);
        when(phonebook.searchContacts("Juan")).thenReturn(Collections.emptyList());

        // When
        controller.handleSearchContacts(); // First search

        // Then
        //verify(view, times(2)).showMessage("Enter search query: ");
        verify(phonebook).searchContacts("John");
        verify(view, times(2)).showSearchMenu();  // Adjusted to check for 2 calls

        // When 'again' is selected, search again with a different query
        controller.handleSearchContacts(); // Second search

        // Then, verify the second search happens with the query 'Juan'
        verify(phonebook).searchContacts("Juan");
        //verify(view).showSearchMenu();

        // Verify the message for no results
        //verify(view).showMessage("No results found ");
    }




    @Test
    public void test_back_command_returns_to_menu() {
        // Given
        ContactsView view = mock(ContactsView.class);
        Phonebook phonebook = mock(Phonebook.class);
        ContactsController controller = new ContactsController(phonebook, view);
        List<AbstractRecord> results = Arrays.asList(mock(AbstractRecord.class));

        when(view.getUserInput()).thenReturn("test", "back");
        when(phonebook.searchContacts("test")).thenReturn(results);

        // When
        controller.handleSearchContacts();

        // Then
        verify(view, times(1)).showSearchMenu();
    }

}