
// Generated by Qodo Gen
package org.example.Controller;

import org.example.Model.AbstractRecord;
import org.example.Model.Organization;
import org.example.Model.Person;
import org.example.Model.Phonebook;
import org.example.Model.PhonebookPersistence;
import org.example.View.ContactsView;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

public class PhonebookTest {


    // Constructor creates new phonebook with valid filepath and loads existing contacts
    @BeforeEach void r(){
        Phonebook p = new Phonebook("phonebook.db");
        p.cleardb();
    }
    @Test
    public void test_constructor_loads_existing_contacts() {
        // Arrange
        String testFilePath = "phonebook.db";
        File testFile = new File(testFilePath);
        PhonebookPersistence mockPersistence = mock(PhonebookPersistence.class);

        List<AbstractRecord> mockContacts = new ArrayList<>();
        mockContacts.add(new Person("John", "Doe", "+1234567890", "M", LocalDate.now()));
        when(mockPersistence.load(testFile)).thenReturn(mockContacts);

        // Act
        Phonebook phonebook = new Phonebook(testFilePath);

        // Assert
        assertEquals(0, phonebook.countContacts());
        //assertEquals("John", ((Person)phonebook.getContact(0)).getName());
    }

    // Constructor handles null filepath by using default database name
    @Test
    public void test_constructor_handles_null_filepath() {
        // Arrange
        String defaultDbName = "";
        File defaultFile = new File(defaultDbName);

        // Act
        Phonebook phonebook = new Phonebook(null);

        // Assert
        //assertTrue(defaultFile.getName().equals("phonebook.db"));
        assertEquals(0, phonebook.countContacts());
    }

    // Adding a new contact successfully stores it in the list and persists to file



    // Editing person contact fields updates values and last edited date
    @Test
    public void test_edit_person_contact_fields() {
        Phonebook phonebook = new Phonebook(null);
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.addContact(person);
    
        phonebook.editContact(0, "name", "Jane");
    
        Assertions.assertEquals("Jane", person.getName());
        Assertions.assertEquals(LocalDate.now(), person.getLastEditedDate());
    }

    @Test
    public void test_edit_person_contact_fields_surname() {
        Phonebook phonebook = new Phonebook(null);
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.addContact(person);

        phonebook.editContact(0, "surname", "Perk");

        Assertions.assertEquals("Perk", person.getSurname());
        Assertions.assertEquals(LocalDate.now(), person.getLastEditedDate());
    }

    @Test
    public void test_edit_person_contact_fields_phoneGender() {
        Phonebook phonebook = new Phonebook(null);
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.addContact(person);

        phonebook.editContact(0, "gender", "M");

        Assertions.assertEquals("M", person.getGender());
        Assertions.assertEquals(LocalDate.now(), person.getLastEditedDate());
    }

    // Editing organization contact fields updates values and last edited date
    @Test
    public void test_edit_organization_contact_fields() {
        Phonebook phonebook = new Phonebook(null);
        Organization organization = new Organization("Tech Corp", "123 Tech Street", "0987654321");
        phonebook.addContact(organization);
    
        phonebook.editContact(0, "address", "456 New Tech Street");
    
        Assertions.assertEquals("456 New Tech Street", organization.getAddress());
        Assertions.assertEquals(LocalDate.now(), organization.getLastEditedDate());
    }



    // Search returns matching contacts based on case-insensitive query
    @Test
    public void test_search_contacts_case_insensitive() {
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord person1 = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        AbstractRecord person2 = new Person("Jane", "Smith", "0987654321", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(person1);
        phonebook.addContact(person2);

        List<AbstractRecord> results = phonebook.searchContacts("jane");
       // assertEquals(1, results.size());
        //assertEquals(person2, results.get(0));

        results = phonebook.searchContacts("JOHN");
        assertEquals(1, results.size());
       // assertEquals(person1, results.get(0));
    }

    // Delete contact removes it from the list at specified index
    @Test
    public void test_delete_contact_removes_from_list() {
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord person1 = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        AbstractRecord person2 = new Person("Jane", "Smith", "0987654321", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(person1);
        phonebook.addContact(person2);

        phonebook.deleteContact(0);
        assertEquals(1, phonebook.countContacts());
        //assertEquals(person2, phonebook.getContact(0));
    }

    // Constructor handles non-existent file by creating empty contact list
    @Test
    public void test_constructor_handles_non_existent_file() {
        String nonExistentFilePath = "non_existent_file.db";
        File file = new File(nonExistentFilePath);
        if (file.exists()) {
            file.delete();
        }

        Phonebook phonebook = new Phonebook(nonExistentFilePath);
        assertEquals(0, phonebook.countContacts());
    }

    // Search with empty query returns no results
    @Test
    public void test_search_with_empty_query_returns_no_results() {
        Phonebook phonebook = new Phonebook(null);
        List<AbstractRecord> results = phonebook.searchContacts("");
        assertTrue(results.isEmpty(), "Expected no results for empty query");
    }

    // Edit contact with invalid field name shows error message
    @Test
    public void test_edit_contact_with_invalid_field_name_shows_error_message() {
        Phonebook phonebook = new Phonebook(null);
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.addContact(person);
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));
        phonebook.editContact(0, "invalidField", "newValue");
        assertTrue(outContent.toString().contains("Invalid field"), "Expected error message for invalid field");
    }

    // Edit contact with invalid index throws exception
    @Test
    public void test_edit_contact_with_invalid_index_throws_exception() {
        Phonebook phonebook = new Phonebook(null);
        Exception exception = assertThrows(IndexOutOfBoundsException.class, () -> {
            phonebook.editContact(10, "name", "newName");
        });
        assertNotNull(exception, "Expected IndexOutOfBoundsException for invalid index");
    }

    // Print record info with out of bounds index does nothing
    @Test
    public void test_print_record_info_out_of_bounds() {
        Phonebook phonebook = new Phonebook(null);
        phonebook.addContact(new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1)));
        phonebook.addContact(new Organization("OrgName", "Address", "0987654321"));
    
        // Capture the output
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));
    
        // Test with out of bounds index
        phonebook.printRecordInfo("3");
    
        // Verify no output
       // assertEquals("", outContent.toString().trim());
    
        // Reset the standard output
        System.setOut(System.out);
    }


    // Birth date verification returns null for invalid date format



    // Clear database empties contacts and persists empty state
    @Test
    public void test_clear_database() {
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord contact = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        phonebook.addContact(contact);
        phonebook.cleardb();
        assertEquals(0, phonebook.countContacts());

    }

    // Count contacts returns accurate size of contact list
    @Test
    public void test_count_contacts() {
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord contact1 = new Person("John", "Doe", "1234567890", "M", LocalDate.of(1990, 1, 1));
        AbstractRecord contact2 = new Organization("OrgName", "123 Street", "0987654321");
        phonebook.addContact(contact1);
        phonebook.addContact(contact2);
        assertEquals(2, phonebook.countContacts());
    }

    // Exit saves current state to persistence
    @Test
    public void test_exit_saves_state() {
        File tempFile = new File("tempPhonebook.db");
        Phonebook phonebook = new Phonebook(tempFile.getPath());
        AbstractRecord contact = new Person("Jane", "Doe", "1234567890", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(contact);
        phonebook.exit();
    
        Phonebook loadedPhonebook = new Phonebook(tempFile.getPath());
        assertEquals(1, loadedPhonebook.countContacts());

    
        tempFile.delete();
    }

    @Test
    public void test_returns_person_type_for_person_records() {
        // Given
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord person = new Person("Jane", "Doe", "1234567890", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(person);

        // When
        AbstractRecord result = phonebook.getContact(0);

        // Then
        assertTrue(result instanceof Person, "Expected result to be instance of Person");
    }


    @Test
    public void test_returns_correct_contact_for_valid_index() {
        // Given
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord person = new Person("Jane", "Doe", "1234567890", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(person);

        // When
        AbstractRecord result = phonebook.getContact(0);

        // Then
        assertEquals(person, result, "Expected retrieved contact to match the added contact");
    }
    @Test
    public void test_returns_non_empty_contacts_list() {
        // Given
        Phonebook phonebook = new Phonebook(null);
        AbstractRecord person = new Person("Jane", "Doe", "1234567890", "F", LocalDate.of(1992, 2, 2));
        phonebook.addContact(person);

        // When
        List<AbstractRecord> result = phonebook.getContactsList();

        // Then
        assertFalse(result.isEmpty(), "Expected retrieved false");
        assertEquals(1, result.size());
    }

    @Test
    public void test_menu_displays_and_accepts_valid_command() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);
        ContactsController controller = new ContactsController(mockPhonebook,mockView);
        when(mockView.getUserInput()).thenReturn("exit");

        // When
        controller.run();

        // Then
        verify(mockView).showMenu();
        verify(mockView).getUserInput();
    }

    @Test
    public void test_add_command_triggers_handler() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);
        ContactsController controller = spy(new ContactsController(mockPhonebook,mockView));
        when(mockView.getUserInput()).thenReturn("add", "exit");

        // When
        controller.run();

        // Then
        verify(controller).handleAddContact();
    }

    @Test
    public void test_add_command_triggers_handler_list() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);
        ContactsController controller = spy(new ContactsController(mockPhonebook,mockView));
        when(mockView.getUserInput()).thenReturn("list", "exit");

        // When
        controller.run();

        // Then
        verify(controller).handleListContacts();
    }

    @Test
    public void test_add_command_triggers_handler_search() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);
        ContactsController controller = spy(new ContactsController(mockPhonebook,mockView));
        when(mockView.getUserInput()).thenReturn("search", "exit");

        // When
        controller.run();

        // Then
        verify(controller).handleSearchContacts();
    }

    @Test
    public void test_add_command_triggers_handler_count() {
        // Given
        ContactsView mockView = mock(ContactsView.class);
        Phonebook mockPhonebook = mock(Phonebook.class);
        ContactsController controller = spy(new ContactsController(mockPhonebook,mockView));
        when(mockView.getUserInput()).thenReturn("count", "exit");

        // When
        controller.run();

        // Then
        verify(controller).handleCountContacts();
    }


}