package org.example.Model;
// Generated by Qodo Gen

import org.example.Model.Person;

import org.junit.Test;

import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.time.LocalDate;
import java.util.List;

import static org.junit.Assert.*;

public class PersonTest {


    // Constructor correctly initializes Person object with all fields
    @Test
    public void test_constructor_initializes_all_fields_correctly() {
        // Given
        String name = "John";
        String surname = "Doe";
        String phone = "1234567890";
        String gender = "M";
        LocalDate birthDate = LocalDate.of(1990, 1, 1);
    
        // When
        Person person = new Person(name, surname, phone, gender, birthDate);
    
        // Then
        assertEquals(name, person.getName());
        assertEquals(surname, person.getSurname());
        assertEquals(phone, person.getPhoneNumber());
        assertEquals(gender, person.getGender());
        assertEquals(birthDate, person.getBirthDate());
    }

    // getFields returns correct list of available field names
    @Test
    public void test_get_fields_returns_correct_list() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.now());
        List<String> expectedFields = List.of("name", "surname", "birth", "gender", "number");
    
        // When
        List<String> actualFields = person.getFields();
    
        // Then
        assertEquals(expectedFields, actualFields);
    }

    // setField updates corresponding field values for valid field names
    @Test
    public void test_set_field_updates_values_correctly() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.now());
    
        // When
        person.setField("name", "Jane");
        person.setField("surname", "Smith");
        person.setField("gender", "F");
    
        // Then
        assertEquals("Jane", person.getName());
        assertEquals("Smith", person.getSurname());
        assertEquals("F", person.getGender());
    }

    // getField retrieves correct values for all valid field names
    @Test
    public void test_get_field_retrieves_correct_values() {
        // Given
        LocalDate birthDate = LocalDate.of(1990, 1, 1);
        Person person = new Person("John", "Doe", "1234567890", "M", birthDate);
    
        // When/Then
        assertEquals("John", person.getField("name"));
        assertEquals("Doe", person.getField("surname"));
        assertEquals(birthDate.toString(), person.getField("birth"));
        assertEquals("M", person.getField("gender"));
        assertEquals("1234567890", person.getField("number"));
    }

    // printName returns concatenated name and surname
    @Test
    public void test_print_name_returns_concatenated_name() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.now());
    
        // When
        String fullName = person.printName();
    
        // Then
        assertEquals("John Doe", fullName);
    }

    // setField handles invalid field names by printing error message
    @Test
    public void test_set_field_handles_invalid_field_name() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.now());
        String originalName = person.getName();
    
        // When
        person.setField("invalid_field", "new value");
    
        // Then
        assertEquals(originalName, person.getName());
    }

    // getField returns "[no data]" for null birthDate
    @Test
    public void test_get_field_returns_no_data_for_null_birth_date() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", null);
    
        // When
        String birthDateField = person.getField("birth");
    
        // Then
        assertEquals("[no data]", birthDateField);
    }

    // getField returns "[no data]" for empty gender string
    @Test
    public void test_get_field_returns_no_data_for_empty_gender() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "", LocalDate.now());
    
        // When
        String genderField = person.getField("gender");
    
        // Then
        assertEquals("[no data]", genderField);
    }

    // getField returns "[no data]" for invalid field names
    @Test
    public void test_get_field_returns_no_data_for_invalid_field() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", LocalDate.now());
    
        // When
        String invalidField = person.getField("invalid_field");
    
        // Then
        assertEquals("[no data]", invalidField);
    }

    // printInfo handles null birthDate by displaying "[no data]"
    @Test
    public void test_print_info_handles_null_birth_date() {
        // Given
        Person person = new Person("John", "Doe", "1234567890", "M", null);
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outputStream));
    
        // When
        person.printInfo();
    
        // Then
        String output = outputStream.toString();
        assertTrue(output.contains("Birth date: [no data]"));
    }
}