package org.example.View;
// Generated by Qodo Gen

import org.example.View.ContactsView;

import org.junit.Test;
import org.mockito.Mockito;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.lang.reflect.Field;
import java.util.Scanner;

import static org.junit.Assert.*;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class ContactsViewTest {


    // Menu displays correct options for main menu (add, list, search, count, exit)
    @Test
    public void test_show_menu_displays_correct_options() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showMenu();

        String expectedOutput = "\n[menu] Enter action (add, list, search, count, exit):\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }



    // List menu displays correct options (number, back)


    // Record menu displays correct options (edit, delete, menu)
    @Test
    public void test_show_record_menu_displays_correct_options() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showRecordMenu();

        String expectedOutput = "[record] Enter action (edit, delete, menu):\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }

    // Search menu displays correct options (number, back, again)
    @Test
    public void test_show_search_menu_displays_correct_options() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showSearchMenu();

        String expectedOutput = "[search] Enter action ([number], back, again):\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }

    // getUserInput successfully captures user input from Scanner
    @Test
    public void test_get_user_input_captures_input() {
        String input = "test input";
        InputStream in = new ByteArrayInputStream(input.getBytes());
        System.setIn(in);

        ContactsView contactsView = new ContactsView();
        String userInput = contactsView.getUserInput();

        assertEquals(input, userInput);

        System.setIn(System.in);
    }

    // showMessage correctly prints provided message string
    @Test
    public void test_show_message_prints_correct_string() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        String message = "Test message";
        contactsView.showMessage(message);

        assertEquals("Test message\n", outContent.toString());

        System.setOut(System.out);
    }

    // Scanner handling when input stream is closed
    @Test
    public void test_get_user_input_when_scanner_closed() throws NoSuchFieldException, IllegalAccessException {
        Scanner mockScanner = Mockito.mock(Scanner.class);
        Mockito.when(mockScanner.nextLine()).thenThrow(new IllegalStateException("Scanner closed"));
    
        ContactsView contactsView = new ContactsView();
        Field scannerField = ContactsView.class.getDeclaredField("scanner");
        scannerField.setAccessible(true);
        scannerField.set(contactsView, mockScanner);
    
        assertThrows(IllegalStateException.class, () -> {
            contactsView.getUserInput();
        });
    }

    // System.out handling when print stream is redirected


    // Handling null message in showMessage method
    @Test
    public void test_show_message_handles_null() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showMessage(null);

        String expectedOutput = "null\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }

    // Menu text formatting and alignment consistency
    @Test
    public void test_show_list_menu_displays_correct_options() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showListMenu();

        String expectedOutput = "[list] Enter action ([number], back):\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }



    // Proper newline handling across different OS platforms


    // Multiple rapid menu navigation calls
    @Test
    public void test_multiple_rapid_menu_navigation_calls() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();
        contactsView.showMenu();
        contactsView.showListMenu();
        contactsView.showRecordMenu();
        contactsView.showSearchMenu();

        String expectedOutput = "\n[menu] Enter action (add, list, search, count, exit):\n"
                              + "[list] Enter action ([number], back):\n"
                              + "[record] Enter action (edit, delete, menu):\n"
                              + "[search] Enter action ([number], back, again):\n";
        assertEquals(expectedOutput, outContent.toString());

        System.setOut(System.out);
    }

    // Menu state transitions between different menu types
    @Test
    public void test_menu_state_transitions() {
        ByteArrayOutputStream outContent = new ByteArrayOutputStream();
        System.setOut(new PrintStream(outContent));

        ContactsView contactsView = new ContactsView();

        contactsView.showMenu();
        String expectedMenuOutput = "\n[menu] Enter action (add, list, search, count, exit):\n";
        assertEquals(expectedMenuOutput, outContent.toString());

        outContent.reset();
        contactsView.showListMenu();
        String expectedListMenuOutput = "[list] Enter action ([number], back):\n";
        assertEquals(expectedListMenuOutput, outContent.toString());

        outContent.reset();
        contactsView.showRecordMenu();
        String expectedRecordMenuOutput = "[record] Enter action (edit, delete, menu):\n";
        assertEquals(expectedRecordMenuOutput, outContent.toString());

        outContent.reset();
        contactsView.showSearchMenu();
        String expectedSearchMenuOutput = "[search] Enter action ([number], back, again):\n";
        assertEquals(expectedSearchMenuOutput, outContent.toString());

        System.setOut(System.out);
    }


}